name: woof_to_go
description: "Woof to Go - Tu compaÃ±ero de paseos"

publish_to: 'none'

version: 1.4.8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.3
  image_picker: ^1.0.7 
  cloud_firestore: ^4.13.4
  google_sign_in: ^6.1.5
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/splash/

flutter_icons:
  android: "icon"
  ios: true
  image_path: "assets/icons/icono.png" 
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/splash/Splash.png"
  android: true
  ios: true